### ISSUE TITLE
Release files

### ISSUE THREAD

**Issue by D-Ogi** [t-richards/magnetico#1]
What is the format of the release files? They miss extensions.

**Comment by t-richards** [comment]
The release files are all compiled executable programs. After downloading the file that matches your OS and architecture, you should do something like this to run the binary:

```bash
# Assuming you downloaded magnetico-linux-amd64 for a linux machine with an x86-64 processor
chmod +x magnetico-linux-amd64
./magnetico-linux-amd64
```
